### ISSUE TITLE
Create an Ansible playbook  for an Azure Linux VM.

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#100]
Create an Ansible playbook that will be used for all VMs (devsecops).

What the playbook should configure:
- [x] Azure-cli
- [x] Kubectl

**Comment by ThomasCardin** [comment]
@rngadam do you have any suggestion for the ansible playbook? Some needs that we might have forgotten?

**Comment by rngadam** [comment]
@ThomasCardin as discussed this morning, I wonder if we shouldn't start with automating setup of Azure Machine Learning compute according to the internal documentation first before configuring the internals of each instance?

**Comment by ThomasCardin** [comment]
For now, only a VM for the DevSecOps team has been configured.
