### ISSUE TITLE
As a developer, I would like to work with an instance of Bytebase to manage databases schemas

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#121]
To optimize our database management practices, we are considering the implementation of a standardized schema and data change processes across all our database systems. We are specifically looking at leveraging [Bytebase](https://github.com/bytebase/bytebase) to facilitate this initiative. Bytebase offers a solution that pushes towards adopting "Database-as-code" practices. This approach is in alignment with our existing GitOps methodologies, emphasizing automation, version control, and collaborative workflows.

By integrating Bytebase, we can directly manage our database change scripts within a Version Control System (VCS). This integration enables an automated deployment process through Bytebase, which is triggered upon the detection of new or updated change scripts in the VCS. This capability ensures that our database schemas remain up-to-date and consistent across the board, significantly reducing the risk of discrepancies and enabling smoother, more efficient development cycles.

Useful documentation on self hosting with kubernetes : 
https://www.bytebase.com/docs/get-started/self-host/#kubernetes

Acceptance criteria:
Able to connect to sample instance that will be deployed in issue #9

**Comment by rngadam** [comment]
@Francois-Werbrouck may have a bit more information about Bytebase following the product meeting this morning and should feed some of those feedbacks into the descirption here.

**Comment by Francois-Werbrouck** [comment]
I have more requirements for Bytebase following the meeting and based on the database team needs. I've open an [issue](https://github.com/ai-cfia/ailab-db/issues/95) about our GitOps needs since it is unrelated to having Bytebase self-hosted.
