### ISSUE TITLE
As a developer, I would like to create packages with versioning

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/howard#126]
Can I ask your advice on how I can create python packages with versioning?

Basically, the package should
- be installable via `pip install`
- have versions so that the users can install the ones they need

We currently use `setuptools` and we perform the install like `pip install git+https://github.com/ai-cfia/azure-db.git@main#subdirectory=azure-ai-search`, which is acceptable but we don't know how to version. 

It would even be better if the solution allowed us to manage packages in other languages like `js` or `ts`.

Sorry if this is placed in the wrong repo.

**Comment by rngadam** [comment]
instead of @main use @ on a version tag pointing to the commit of that version?

**Comment by k-allagbe** [comment]
> instead of @main use @ on a version tag pointing to the commit of that version?

Yes that definitely solves versioning for me. Thanks. So the tags would be semver right? We currently dont use release+tag though.

**Comment by rngadam** [comment]
> > instead of @main use @ on a version tag pointing to the commit of that version?
> 
> Yes that definitely solves versioning for me. Thanks. So the tags would be semver right? We currently don't use release+tag though.

Yes, semver. Discuss with @SonOfLope and @ThomasCardin to integrate that action of tagging to version within the Github Workflow

**Comment by SonOfLope** [comment]
Done for the following repositories concerned by this issue :
- Azure-db
- Fertiscan-pipeline
- Ailab-datastore

Used in 
- https://github.com/ai-cfia/fertiscan-pipeline/releases/tag/v0.0.7
- https://github.com/ai-cfia/azure-db/releases/tag/v0.1.1-azure-ai-search
