### ISSUE TITLE
Deploy an OpenTelemetry operator to manage telemetry received from hosted apps

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#13]
In order to allow us to make use of a centralized solution to collect and observe logs, metrics and traces for our applications, we want to make use of the [OpenTelemetry Operator](https://signoz.io/blog/opentelemetry-operator-complete-guide/#opentelemetry-operator-for-kubernetes) which implements the Kubernetes Operator framework to allow us to then deploy a OpenTelemetryCollector (to manage and export data) and inject auto-instrumentation libraries into our workloads (example with python will be implemented).

Acceptance criteria :
- [ ] Deployed the operator via [helm charts](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator)
- [ ] Configure auto-instrumentation and sample a demonstration for python

**Comment by ThomasCardin** [comment]
Deploy OTEL

**Comment by rngadam** [comment]
Developer

![image](https://github.com/ai-cfia/infra/assets/538542/102a9704-3720-4347-8ddc-7bab671e6d9f)
