### ISSUE TITLE
Deploy and configure Falco

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#147]
## Why

Falco is a graduated project from the CNCF and the only project to actively focuses on surveillance and alerting at the kernel level using eBPF. Specifically, Falco focuses on Runtime Security; it is designed to detect anomalous activity and potentially malicious behavior at the system level in real-time.

What is KubeArmor? KubeArmor steps in to actively block and mitigate threats. 

In our case, maybe we can select only one of the two solution. 

## TODO:

- [ ] Deploy Falco
- [ ] Configure Falco
- [ ] Configure Falco dashboards with Grafana

**Comment by rngadam** [comment]
"Falco is a cloud-native security tool designed for Linux systems. It employs custom rules on kernel events, which are enriched with container and Kubernetes metadata, to provide real-time alerts. Falco helps you gain visibility into abnormal behavior, potential security threats, and compliance violations, contributing to comprehensive runtime security."

https://falco.org/

**Comment by ThomasCardin** [comment]
@rngadam ping. The description have been updated. Maybe we can discuss about the tool we want to implement.

**Comment by rngadam** [comment]
> @rngadam ping. The description have been updated. Maybe we can discuss about the tool we want to implement ( Falco or Kubearmor)

ok, let's make sure we have this conversation at the product meeting
