### ISSUE TITLE
Deploy LibreChat to compare with other solutions

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#241]
As part of leveraging the Louis project, we want to start the project with the appropriate base from which to start our development. We already have an instance of openweb ui and wed like to compare its functionalities with those of librachat

Acceptance criteria : 
- Configure litellm with connection to gpt4 and gemini pro
- Make endpoint available from librachat.inspection.alpha.canada.ca

**Comment by nmeraihi** [comment]
Merci pour la quick response :)
