### ISSUE TITLE
Update Secret Version for [Service/Application Name]

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/howard#249]
### ## Issue Description

New version 5

### Related issue

https://github.com/ai-cfia/llamaindex-db/issues/23

### Checklist

- [ ] I have incremented the `avp.kubernetes.io/secret-version` annotation.
 - [ ] I updated the secret manifest with required keys if necessary.
 - [ ] I updated secrets values in Vault

**Comment by SonOfLope** [comment]
Can youj rename title with appropriate application whenever you can.
