### ISSUE TITLE
 As a DevOps, I would like to stop using sidecars for injecting secrets into pods.

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#27]
### Executive summary

The secrets are exposed in clear text within the pod.

## Issue

Currently, secrets for an application (e.g., environment variables in most cases) are injected via sidecars. We want to avoid this to prevent having clear text secrets in the application pods. To achieve this, it would be necessary to pass the secrets as arguments to the image and find an alternative solution for managing the secrets.

## Solution 

The[ vault plugin](https://github.com/argoproj-labs/argocd-vault-plugin) for ArgoCD will be used as a solution. This plugin allows ArgoCD to retrieve secrets from vault and replace placeholders in our manifest files with them before applying them to the cluster. The placeholders allows to specify a version of the secret which aligns with our needs of having the possibility to track changes for secrets. Specifying a version will need a developer to open a PR on the repo with the new version while updating the value of the secret through the vault ui interface. 

### TODO

 - [x] #110
 - [x] Test the solution. Will be tested with https://github.com/ai-cfia/howard/pull/109
 - [x] #111
 - [x] #112

**Comment by rngadam** [comment]
Still unclear as to how sidecar had relevance to secrets management. 

Looking at the list of examples from the following documentation

https://spacelift.io/blog/kubernetes-sidecar-container

... nothing seems to indicate that this typically is typically used for configuring the main container secrets. 

There is "security and authentication", but this relates to mediating external access (for SSO purposes for example).

**Comment by ThomasCardin** [comment]
We found a solution to the `side-car` problem: https://argocd-vault-plugin.readthedocs.io/en/stable/

**Comment by SonOfLope** [comment]
Solution with AVP has proven to work for 
https://github.com/ai-cfia/howard/issues/111
 https://github.com/ai-cfia/howard/issues/112
and documentation added to https://github.com/ai-cfia/howard/blob/main/docs/secrets-management.md
