### ISSUE TITLE
Integrate docker-compose configuration for fertiscan-backend to enable local integration testing

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#272]
Create a docker-compose containing:

- The fertiscan-frontend
- The local Dockerfile of fertiscan-frontend
- Grafana
- Loki
- Prometheus
- Alloy
- Tempo
- Ingress NGINX

**Comment by SonOfLope** [comment]
Out of scope for now. Taking it out of iterations

**Comment by ThomasCardin** [comment]
Won't do, another PR is open for this problem
