### ISSUE TITLE
As a Devops, I would like to rework the file structure in this directory

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#30]
### Executive summary

The purpose of this task is to rework the structure of this repository to make it more understandable for everyone. Some ideas have been proposed

### Exemples
![image](https://github.com/ai-cfia/infra/assets/49320132/e80d14d7-f8b2-440f-919a-284fa49c97e9). 

Considering that we have several open tasks that will enable the management of multiple environments simultaneously, in addition to having different cloud providers. It is essential to establish a structured framework.

### TODO
- [ ] Schedule a meeting to discuss various scenarios.
- [ ] Revise the existing folder structure.

**Comment by rngadam** [comment]
please don't forget to set the Projects field
