### ISSUE TITLE
Resolve scheduling on nodes maxing out capacities of single node

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#318]
**Context:** Currently, most of pods are being scheduled to a single node and this resolves in pod eviction for resources threshold being reached. 

**Solution:** Look into setting affinity rules or lownodeutilization policy to resolve this.

réferences : 
- https://stackoverflow.com/questions/75721791/kubernetes-aks-scheduling-all-pods-to-same-node
- https://github.com/kubernetes-sigs/descheduler#lownodeutilization
- https://learn.microsoft.com/en-us/azure/aks/developer-best-practices-resource-management

**Comment by ThomasCardin** [comment]
Done with: https://github.com/ai-cfia/howard/issues/319
