### ISSUE TITLE
Rename infrastructure project to enhance clarity and reflect purpose

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#32]
The current name of our infrastructure project, simply named 'infra'  lacks specificity and does not convey the unique aspects of our project. This issue proposes renaming the project to a title that more accurately reflects its purpose.

Given the project's approach to leveraging cloud-native technologies for AI-driven solutions, a more evocative and descriptive name would enhance its identity and alignment with our goals. After consideration with @ThomasCardin, the proposed new name for our infrastructure project is "Aether".

Why "Aether"?
In ancient Greek mythology, Aether represents the upper air, clear sky, or the heavens. It  evokes imagery of the sky and the cloud, aligning with our commitment to cloud-native technologies.

**Comment by rngadam** [comment]
Seems like there is already a project with the same codename and significant conceptual overlap?

https://opennetworking.org/aether/

> Aether is wide recognized as the leading open source private 5G platform. It provides a cloud optimized solution running on Kubernetes as native microservices with scaleout. Optimized for the rigors of enterprise Industry 4.0 applications, Aether offers an end-to-end solution that can be deployed with a range of RAN options, including open RAN. Aether is highly scalable enabling users to gain hands-on experience and start with small deployments and scale as requirements expand into large distributed private networks supporting both 4G and 5G connectivity.

**Comment by SonOfLope** [comment]
@rngadam  what about ..

GalaxACIA

**Comment by rngadam** [comment]
> GalaxACIA

Kind of a misspelling of galaxia so I'd be worried we'd confuse it all the time. It is also hard to pronounce out loud and to transcribe correctly when heard.

How about just galax?

>Galax, the wandplant, wandflower, or beetleweed, is a genus in the flowering plant family Diapensiaceae, containing a single species, Galax urceolata (syn. G. rotundifolia, G. aphylla). It is native to the southeastern United States from Massachusetts and New York south to northern Alabama, growing mainly in the Appalachian Mountains at altitudes of up to 1,500 m, where it grows in shaded places in forests. 

https://en.wikipedia.org/wiki/Galax

It's also a computer hardware company, a trading company, a pork company so no direct overlap. 

although downside it is an US native plant, not a Canadian one.

Alternatively, how about a plain name to follow with louis, mcluhan, etc. How about Howard?

> Luke Howard, FRS (28 November 1772 – 21 March 1864) was a British manufacturing chemist and an amateur meteorologist with broad interests in science.[1] His lasting contribution to science is a nomenclature system for clouds, which he proposed in an 1802 presentation to the Askesian Society. Because of this, Howard is referred to as "The Godfather of Clouds", the "namer of the clouds", and the "father of meteorology".

https://en.wikipedia.org/wiki/Luke_Howard

**Comment by SonOfLope** [comment]
I like it!  @ThomasCardin thoughts ?

**Comment by rngadam** [comment]
> I like it! @ThomasCardin thoughts ?

galax or howard?

**Comment by SonOfLope** [comment]
Sorry. Howard! seems appropriate since it relates to how we named other projects and a reference to "The Godfather of Clouds" is awesome.

**Comment by ThomasCardin** [comment]
Howard is nice!

**Comment by ThomasCardin** [comment]
Done
