### ISSUE TITLE
As a Devops, I want  to improve the structure of the kubernetes/ folder

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#49]
The `kubernetes/ ` folder contains multiple manifests used to create resources in Kubernetes. Given that the environments in the two cloud providers do not evolve at the same speed (e.g. we aren't currently using GCP anymore), it would be necessary to segment the manifests so that the Kubernetes (k8s) environment of a provider is easily replicable.

**Comment by ThomasCardin** [comment]
See https://github.com/ai-cfia/howard/pull/46 for a proposed suggestion

**Comment by SonOfLope** [comment]
Should we have a common folder to avoid duplicates for system's/services that are agnostic to the provider used ?

**Comment by ThomasCardin** [comment]
Yes
