### ISSUE TITLE
As a DevSecOps, I would like to secure my ecosystem

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#59]
## Executive Summary

Currently, only one tool is in place to analyze the code of the directories. With the growing infrastructure, an analysis was conducted to ensure that each component of the infrastructure (as well as the code executed in the containers) is scanned by a security tool to identify potential vulnerable dependencies and poor programming practices.

## Context

Currently, we only have one tool that allows us to analyze the source code of the directories. In this sense, we want to have more tools to analyze the following components:

- Code scanning
- Docker image scanning
- Infrastructure security scanning and monitoring
    - Policy
    - Resource access control
- Versioning of dependencies

These use cases will cover the vast majority of potential vulnerabilities that could exist on our infrastructure. Once these tools are in place, a monitoring system will be put in place to visualize vulnerabilities and perform audits on applications and infrastructure.

## TODO

- [x] #145
- [x] #146
- [x] #147
- [x] #150
- [x] #149
- [x] #68
    - [x] #69
    - [x] Configure custom dashboards with Prometheus query. This might include reviewing helm charts deployed to enable Prometheus metrics

**Comment by SonOfLope** [comment]
Add between context and todo a section to explain vision and proposed solution (explaining trivy, etc)

**Comment by ThomasCardin** [comment]
> Add between context and todo a section to explain vision and proposed solution (explaining trivy, etc)

Done with description inside each issues.

**Comment by SonOfLope** [comment]
Amazing 🔥

**Comment by ThomasCardin** [comment]
Yesssssir
