### ISSUE TITLE
Deploy Ory Kratos on AKS: Set up Kratos for identity management using Azure AD as Identity provider, enabling users to authenticate with their Azure AD credentials.

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#67]
Set up Kratos for identity management using Azure AD as Identity provider.
TODO 
- [ ] Create manifest files for deployment
  - [ ] Kratos manifest files
  - [ ] Postgres deployment (Kratos needs a postgres instance)
- [ ] Get app registration on Azure
- [ ] Configure Kratos siocial sign in with an app registration to auth users from Azure

**Comment by rngadam** [comment]
The Postgresql integration is intriguing!

**Comment by rngadam** [comment]
@SonOfLope this was closed with the checklist not being completed

**Comment by SonOfLope** [comment]
Will be replaced in : https://github.com/ai-cfia/howard/issues/74
Which provides explanation. Thank you
