### ISSUE TITLE
As a DevSecOps, I would like to backup my data

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#76]
## Executive summary

The goal is to back up all data from a Persistent Volume Claim (PVC) or other storage solution within the Kubernetes cluster.

## Context

Currently, we use PVCs to ensure data persistence within applications, but we do not have a backup solution in case of a disaster.

## TODO

- [x] #347
- [x] #348
- [x] #349
- [x] #350

**Comment by rngadam** [comment]
Also important step: 

* test recovery procedure (probably schedule tests on a regular basis)
* document recovery procedure

**Comment by ThomasCardin** [comment]
See: https://learn.microsoft.com/en-us/azure/backup/azure-kubernetes-service-backup-overview
