### ISSUE TITLE
As a DevSecOps, I want to provide a cloud development environment inside Kubernetes.

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#77]
## Executive Summary

The goal is to allow developers to use their tools, which would normally be installed on their local workstations, in the cloud.

## Context

In order to enable this type of environment, development tools such as VSCode and dbeaver must be available in the cloud. There are several cloud-based development tools available to replace VSCode, but they come at a cost. Some of these tools include GitPod, Coder, Codespace, KubeVirt or just VM's inside Azure 

Coder is an open-source (free, but with many missing features if we don't pay) solution that allows for cloud-based development while meeting all the criteria required by developers. The same is true for GitPod and Codespace. Currently, our developers are familiar with Codespace, but many of them have reached their daily usage time limit on this platform.

An analysis of Coder, Gitpod, Codespace, KubeViRT and VM's inside Azure needs to be done to see which one would be the most cost-effective and efficient.

## Tasks to be completed

- [x] #78
- [x] #79
- [x] #106
- [x] #100
- [x] #116
- [ ] #101
- [ ] #103
- [x] #102
- [x] #309

**Comment by rngadam** [comment]
Documentation + training material should also be part of the list of tasks.

**Comment by ThomasCardin** [comment]
See: https://www.linkedin.com/pulse/time-speed-up-micro-service-development-deploy-web-based-ian-payne-yxdie/ with https://github.com/linuxserver/docker-webtop

**Comment by ThomasCardin** [comment]
Won't do, see: https://github.com/ai-cfia/howard/issues/399 for our new "solution"
