### ISSUE TITLE
Evaluate cloud-hosted IDE (Integrated Development Environment)

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#78]
Make sure Coder, Gitpod and Codespace provide theses features: 
 
 Coder:
 
 - [x] Port forwarding
 - [x] Install dependencies inside the environement
 - [x] Customize the environment and make sure it has persistence. This environment must be specific to the developer.
 - [x] Access to staging secrets via Vault
 - [x] Analyse the cost
 
 Gitpod

 - [x] Port forwarding
 - [x] Install dependencies inside the environement
 - [x] Customize the environment and make sure it has persistence. This environment must be specific to the developer.
 - [x] Access to staging secrets via Vault https://www.gitpod.io/docs/configure/repositories/environment-variables
 - [x] Analyse the cost
 
 Codespace
 
 - [x] Port forwarding
 - [x] Install dependencies inside the environement
 - [ ] Customize the environment and make sure it has persistence. This environment must be specific to the developer. :x: 
 - [ ] Access to staging secrets via Vault :x: 
 - [x] Analyse the cost

KubeVirt
 - [x] Port forwarding
 - [x] Install dependencies inside the environement
 - [x] Customize the environment and make sure it has persistence. This environment must be specific to the developer.
 - [x] Access to staging secrets via Vault
 - [ ] Analyse the cost

**Comment by ThomasCardin** [comment]
Port forwarding -> https://coder.com/docs/v2/latest/networking/port-forwarding
Access to staging secrets via Vault -> This can be done using the side-car pattern used by vault. 
Install dependencies inside the Coder environement -> Can be done.
Customize the environment and make sure it has persistence. This environment must be specific to the developer. -> Can be done.

**Comment by rngadam** [comment]
"Evaluate cloud-hosted IDE (Integrated Development Environment)"

**Comment by ThomasCardin** [comment]
> "Evaluate cloud-hosted IDE (Integrated Development Environment)"

I like it

**Comment by ThomasCardin** [comment]
## Cost Analysis for Each Proposed Solution

Coder: Need to check with the sales team for an accurate quote.
Gitpod: $0.36 US / hour
Codespace: $0.36 US / hour with 4 cores per developer
KubeVirt: The price is included in the costs of our existing Kubernetes cluster.

**Comment by rngadam** [comment]
KubeVirt seems to be a completely different kettle of fish. Also a bit unfair not to try to at least estimate the cost of the underlying VM needed to run the cluster to keep that solution up.

Also note that the solution needs to work with the https://containers.dev/ (defined in our .devcontainer in each of our projects).

We also had specifically the discussion about ensuring that the vault secrets would be accessible from Codespaces so surprised to see that this is not supported now.

**Comment by ThomasCardin** [comment]
> KubeVirt seems to be a completely different kettle of fish. Also a bit unfair not to try to at least estimate the cost of the underlying VM needed to run the cluster to keep that solution up.

Fair enough to estimate the price. In this situation, KubeVirt would allow us to manage many cases where we have no control. For example, installing development tools like DBeaver, admin access, etc.

> Also note that the solution needs to work with the https://containers.dev/ (defined in our .devcontainer in each of our projects).

The developers don't like .devcontainer because it's not their own configuration but a global configuration for every developer that wants to contribute to the project. It's not flexible to the developer specific needs.

> We also had specifically the discussion about ensuring that the vault secrets would be accessible from Codespaces so surprised to see that this is not supported now.

We had this discussion for about 5 minutes. We never mentioned that the solution would be secure and functional. Also, we only mentioned Coder and Gitpod as potential Vault integration options, not Codespaces.

**Comment by rngadam** [comment]
> The developers don't like .devcontainer because it's not their own configuration but a global configuration for every developer that wants to contribute to the project. It's not flexible to the developer specific needs.

.devcontainer is made up to reduce the amount of setup and divergence in our development environment, easing in integration of new developers to products. which specific flexibility is required?

**Comment by ThomasCardin** [comment]
> .devcontainer is made up to reduce the amount of setup and divergence in our development environment, easing in integration of new developers to products. which specific flexibility is required?

Here's a few:

- Custom theme
- Vim binding? 
- Font size and style
- Terminal style
- Keyboard shortcut
- Debugger style
- Specific file management
- Specific language (french or english)

Also to continue my point on KubeVirt:

Depending on the project the developer is working on, they will have all the necessary tools for development through their virtual machine, as we will create it with ansible.

Ansible is a powerful tool that allows you to configure and manage servers, in our case virtual machines. It uses a playbook-based approach, which are YAML files describing the configurations to be applied to the machines.

Here is an example of how we could replace DevContainers with an Ansible playbook:

```yaml
- name: Update apt and install required system packages
  apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
    state: latest
    update_cache: true
```

In this example, we update the mirrors and install the required system packages. This clearly shows a case where a developer would want to add a CLI to test X, Y, Z.

With Ansible, simply modify the playbook and apply the changes for all developers (specifically, all virtual machines) assuming they would likely want the same thing.

Following up on flexibility here's the benefits of using Ansible for development environment management:

- Increased flexibility: Developers can have custom environments tailored to their specific needs.
- Better version management: Ansible playbooks allow you to track and version the configurations of virtual machines.
- More consistent environment: All virtual machines can be configured in the same way, ensuring a consistent development environment for all developers.
- Time and effort saving: Configurations can be easily reproduced and shared between team members.

**Comment by ThomasCardin** [comment]
Closing this issue, we will talk about the analysis made tomorrow morning
