### ISSUE TITLE
Deploy and configure the chosen cloud based IDE for all developers in the organization. Include documentation and training

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#80]
Deploy and configure the chosen cloud based IDE for all developers in the organization, providing them with a personal and configurable work environment.

**Comment by rngadam** [comment]
Should we be closing issues providing functionalities to developers before developers have had a chance to test it and accept the functionality?

**Comment by ThomasCardin** [comment]
Totally agree. Also, before closing a pull request, documentation and training should be provided it the content of it impact developers directly.
