### ISSUE TITLE
Deploy and configure Cloudbeaver. Include documentation and training

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#81]
Deploy Cloudbeaver to allow database administrators (DBAs) to manage their databases with a graphical user interface (UI).

**Comment by rngadam** [comment]
In issues, would suggest keeping the desired high-level functionality (cloud hosted interactive SQL client for Postgresql database) from the implementation (cloudbeaver) to keep the door open to alternative solutions. Similar situation with cloud-hosted IDE (functionality) vs Gitpod/Codespaces/Coder (implementation).

**Comment by ThomasCardin** [comment]
We might not need the use of Cloudbeaver if we use KubeVirt

**Comment by ThomasCardin** [comment]
Won't do. See https://github.com/ai-cfia/howard/issues/77 for more information
