### ISSUE TITLE
As a developer, I would like to deploy postgresml

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#9]
Deploy postgresML on a kubernetes cluster.

**Comment by rngadam** [comment]
The user (developer)  that it is on a Kubernetes cluster.

rework description into this direction (example)

* access using email account (Microsoft Entra) or application user/password
* access through python code in psycopg3
* access through psql command-line
* access through a cloud hosted jupyter notebook
* reliable data storage
* AI model management built-in 
* custom set of postgresql extensions.

**Comment by SonOfLope** [comment]
This is no longer a requirement
